package drivers

import (
	_ "github.com/gweffectx/safedav/drivers/115"
	_ "github.com/gweffectx/safedav/drivers/115_share"
	_ "github.com/gweffectx/safedav/drivers/123"
	_ "github.com/gweffectx/safedav/drivers/123_link"
	_ "github.com/gweffectx/safedav/drivers/123_share"
	_ "github.com/gweffectx/safedav/drivers/139"
	_ "github.com/gweffectx/safedav/drivers/189"
	_ "github.com/gweffectx/safedav/drivers/189pc"
	_ "github.com/gweffectx/safedav/drivers/alias"
	_ "github.com/gweffectx/safedav/drivers/alist_v2"
	_ "github.com/gweffectx/safedav/drivers/alist_v3"
	_ "github.com/gweffectx/safedav/drivers/aliyundrive"
	_ "github.com/gweffectx/safedav/drivers/aliyundrive_open"
	_ "github.com/gweffectx/safedav/drivers/aliyundrive_share"
	_ "github.com/gweffectx/safedav/drivers/baidu_netdisk"
	_ "github.com/gweffectx/safedav/drivers/baidu_photo"
	_ "github.com/gweffectx/safedav/drivers/baidu_share"
	_ "github.com/gweffectx/safedav/drivers/chaoxing"
	_ "github.com/gweffectx/safedav/drivers/cloudreve"
	_ "github.com/gweffectx/safedav/drivers/crypt"
	_ "github.com/gweffectx/safedav/drivers/dropbox"
	_ "github.com/gweffectx/safedav/drivers/ftp"
	_ "github.com/gweffectx/safedav/drivers/google_drive"
	_ "github.com/gweffectx/safedav/drivers/google_photo"
	_ "github.com/gweffectx/safedav/drivers/ipfs_api"
	_ "github.com/gweffectx/safedav/drivers/lanzou"
	_ "github.com/gweffectx/safedav/drivers/local"
	_ "github.com/gweffectx/safedav/drivers/mediatrack"
	_ "github.com/gweffectx/safedav/drivers/mega"
	_ "github.com/gweffectx/safedav/drivers/mopan"
	_ "github.com/gweffectx/safedav/drivers/onedrive"
	_ "github.com/gweffectx/safedav/drivers/onedrive_app"
	_ "github.com/gweffectx/safedav/drivers/pikpak"
	_ "github.com/gweffectx/safedav/drivers/pikpak_share"
	_ "github.com/gweffectx/safedav/drivers/quark_uc"
	_ "github.com/gweffectx/safedav/drivers/s3"
	_ "github.com/gweffectx/safedav/drivers/seafile"
	_ "github.com/gweffectx/safedav/drivers/sftp"
	_ "github.com/gweffectx/safedav/drivers/smb"
	_ "github.com/gweffectx/safedav/drivers/teambition"
	_ "github.com/gweffectx/safedav/drivers/terabox"
	_ "github.com/gweffectx/safedav/drivers/thunder"
	_ "github.com/gweffectx/safedav/drivers/trainbit"
	_ "github.com/gweffectx/safedav/drivers/url_tree"
	_ "github.com/gweffectx/safedav/drivers/uss"
	_ "github.com/gweffectx/safedav/drivers/virtual"
	_ "github.com/gweffectx/safedav/drivers/vtencent"
	_ "github.com/gweffectx/safedav/drivers/webdav"
	_ "github.com/gweffectx/safedav/drivers/weiyun"
	_ "github.com/gweffectx/safedav/drivers/wopan"
	_ "github.com/gweffectx/safedav/drivers/yandex_disk"
)

// All do nothing,just for import
// same as _ import
func All() {

}
